### ISSUE TITLE
Support for Koa v2.x

### ISSUE THREAD

**Issue by SokolskyNikita** [bahmutov/koa-slow#2]
Hello Gleb,

I was wondering if anyone is working on migrating this middleware to Koa v.2.x?

If not, can I do an implementation? I should be done by end of next week, at the latest. 

Thank you.

**Comment by bahmutov** [comment]
sure, go ahead, I am not working on koa 2 yet - prefer running the server without transpiling

**Comment by bahmutov** [comment]
ok, published your pull request and dependency upgrade as v2, thanks for the work!
